# Generated by Django 5.2.4 on 2025-08-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_massage_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
